name: Playwright Automation

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Instalar dependências
        run: npm install
        
      - name: Instalar navegadores do Playwright
        run: npx playwright install

      - name: Executar o script
        run: node sc.js

      - name: Upload de vídeos e arquivos
        uses: actions/upload-artifact@v4
        with:
          name: artefatos-playwright
          path: |
            downloads/
            videos/
